### ISSUE TITLE
Large Repository Size

### ISSUE THREAD

**Issue by RajwolChapagain** [fmcnallyi3/icetop-cnn#6]
The repository size is 2G because of a large .pack file in .git/objects/pack/ causing sluggish clones and VSCode's inability to watch for file changes by default. Possible cause is the inclusion of notebook outputs in old commits.
![image](https://github.com/user-attachments/assets/ae1159c1-4a1d-4d2d-990f-0e297ee66048)
![image](https://github.com/user-attachments/assets/bfe960db-4bd2-406d-ba70-6556b806f685)

**Comment by EthanDorr** [comment]
Deleting unnecessary branches has fixed the issue.
