### ISSUE TITLE
Can't Use --predict as Last Option While Executing submit.py

### ISSUE THREAD

**Issue by RajwolChapagain** [fmcnallyi3/icetop-cnn#7]
While executing submit.py, --help shows that -p (--predict) can be used as the last option before entering the model name. However, doing so causes an invalid choice error.
![image](https://github.com/user-attachments/assets/7faf4c7e-d310-4399-8c0c-f7c0373f1635)

**Comment by EthanDorr** [comment]
The --help message is automatically generated as part of argparse. I can look further into the options for each argument to see if there is a specific configuration of options that allows us to have a positional argument anywhere.
